# 1. Используем официальный базовый образ Python 3.11
FROM python:3.11-slim

# 2. Устанавливаем рабочую директорию в контейнере
WORKDIR /app

# 3. Копируем файл зависимостей requirements.txt в контейнер
COPY requirements.txt .

# 4. Устанавливаем зависимости с помощью pip
RUN pip install --no-cache-dir -r requirements.txt

# 5. Копируем весь исходный код приложения в контейнер
COPY . .

# 6. Открываем порт 8010 для доступа к приложению
EXPOSE 8010

# 7. Указываем команду для запуска приложения через gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:8010", "wsgi:app"]
