version: '3'
services:
  flask_app:
    build: .
    ports:
      - "8010:8010"  # Открываем порт 8010 для доступа к приложению
    volumes:
      - .:/app  # Монтируем директорию с проектом
    restart: always  # Автоматически перезапускать контейнер при сбоях
